spring:
  application:
    name: dubbo-provider-2


project:
  service:
    version: 1.0.0
dubbo:
  scan:
    base-packages: com.middol.dubboprovider2.service.impl
  application:
    name: ${spring.application.name}
  protocol:
    port: 20881
    name: dubbo
    id: dubbo
  registry:
    # 配置多个zookeeper集群中的多个服务器所在地址
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181